version: "3"

services:
  tech-challenge-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3333
  tech-challenge-db:
    image: bitnami/postgresql
    volumes:
      - db_data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=ps123
      - POSTGRESQL_DATABASE=tech-challenge

volumes:
  db_data:
