version: "3"

services:
  tech-challenge-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=ps123
      - POSTGRESQL_DATABASE=tech-challenge
