# @name get-clients
GET http://localhost:3333/clients

###

# @name get-client-by-id
GET http://localhost:3333/clients/149d4cff-a8e2-44cf-b949-f3aad598d1ee

### 

# @name create-client
POST http://localhost:3333/clients  
content-type: application/json

{
    "email": "john.doe2@gmail.com",
    "name": "John Doe2",
    "taxVat": "13311312"
}

### 

# @name edit-client
PUT http://localhost:3333/clients/1198eaa6-8d4d-450b-8561-ce867c8c88cc
content-type: application/json

{
    "email": "john.23@gmail.com",
    "name": "John Doe ALTERED"
}


