# @name get-combos
GET http://localhost:3333/combos?page=1&pageSize=2

###

# @name get-combo-by-id
GET http://localhost:3333/combos/e4215989-9148-4650-a375-be5bae3778ac

### 

# @name create-combo
POST http://localhost:3333/combos  
content-type: application/json

{
  "sandwichId": "657401ee-5abb-4436-9a91-d03059dfcd1c",
  "drinkId": "d824ba54-eafb-4846-99b3-e566b8cc74ae"
}

### 

# @name edit-combo
PUT http://localhost:3333/combos/e4215989-9148-4650-a375-be5bae3778ac
content-type: application/json

{
  "name": "altered",
  "description": "altered",
  "sandwichId": "657401ee-5abb-4436-9a91-d03059dfcd1c",
  "sideId": "",
  "dessertId": ""
}

