# @name get-combos
GET http://localhost:3333/combos

###

# @name get-combo-by-id
GET http://localhost:3333/combos/5a55ead7-17a7-4b70-b513-444338125ae5

### 

# @name create-combo
POST http://localhost:3333/combos  
content-type: application/json

{
  "sandwichId": "095181e8-62f6-4e78-8de9-d01ed812fa2c",
  "sideId": "1d697fac-7069-4681-a2fb-c3af02e429e2"
}

### 

# @name edit-combo
PUT http://localhost:3333/combos/5a55ead7-17a7-4b70-b513-444338125ae5
content-type: application/json

{
  "sandwichId": "095181e8-62f6-4e78-8de9-d01ed812fa2c",
  "sideId": "1d697fac-7069-4681-a2fb-c3af02e429e2",
  "drinkId": "72fdfbe1-618d-4837-bfdf-d79ad26fe9bd"
}

