# @name get-orders
GET http://localhost:3333/orders

###

# @name get-order-by-id 
GET http://localhost:3333/orders/1676f8da-6649-47c3-bab7-30a34477de7c

### 

# @name create-order
POST http://localhost:3333/orders  
content-type: application/json

{
  "clientId": "eeaa256e-bda4-486f-8b19-d59d4cf3e23a",
  "paymentMethod": "QR_CODE",
  "paymentStatus": "PENDING_PAYMENT",
  "combos": [
    {
      "sandwichId": "095181e8-62f6-4e78-8de9-d01ed812fa2c",
      "sideId": "1d697fac-7069-4681-a2fb-c3af02e429e2",
      "drinkId": "3fb830eb-6e5f-49ae-a796-d8486460bd01",
      "quantity": 10,
      "annotation": "remove the tomatos"
    }
  ]
}

### 


# @name update-order-status
PATCH http://localhost:3333/orders/4eb25524-5bae-4937-80a5-24e62a29bd28
content-type: application/json

{
  "status": "READY"
}


