# @name get-orders
GET http://localhost:3333/orders

###

# @name get-order-by-id
GET http://localhost:3333/orders/8b53b50d-51cb-4f47-abf2-f1618b60afba

### 

# @name create-order
POST http://localhost:3333/orders  
content-type: application/json

{
  "visitorName": "John Doe",
  "paymentMethod": "QR_CODE",
  "paymentStatus": "PENDING_PAYMENT",
  "combos": [
    {
      "sandwichId": "4acff47b-78e2-49ed-89e6-4265f97c87ad",
      "sideId": "52952605-5deb-45fe-934d-04450edb085a",
      "drinkId": "277b94da-683e-40ca-bad1-3ed7990fb902",
      "quantity": 10,
      "annotation": "remove the tomatos"
    }
  ]
}

### 


# @name update-order-status
PATCH http://localhost:3333/orders/66ca3720-ec31-412d-9db5-8fb7ffca9961  
content-type: application/json

{
  "status": "PAID"
}


