# @name get-products
GET http://localhost:3333/products

### 

# @name get-product-by-id
GET http://localhost:3333/products/657401ee-5abb-4436-9a91-d03059dfcd1c

### 

# @name create-product
POST http://localhost:3333/products
content-type: application/json

{
  "name": "Lanche de costela",
  "description": "lanche de costela",
  "price": 25,
  "category": "SANDWICH"
}

### 

# @name edit-product
PUT http://localhost:3333/products/150ee6db-c9b4-4351-990d-1d73046f851d
content-type: application/json

{
  "name": "hamburguer de costela 2",
  "price": 20,
  "description": "hamburguer de costela",
  "category": "DESSERT"
}
